services:
  losi-online:
    container_name: "losi-online"
    build:
      args:
        - "COMMIT_HASH=${COMMIT_HASH}"
        - "PUBLIC_LAST_FM_USER=${PUBLIC_LAST_FM_USER}"
        - "PUBLIC_LAST_FM_API_KEY=${PUBLIC_LAST_FM_API_KEY}"
      context: "../../../.."
      dockerfile: "Dockerfile"
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - "PUBLIC_LAST_FM_USER=${PUBLIC_LAST_FM_USER}"
      - "PUBLIC_LAST_FM_API_KEY=${PUBLIC_LAST_FM_API_KEY}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.losi-online.entryPoints=webSecure"
      - "traefik.http.routers.losi-online.rule=Host(`ocd.beauty`)"
      - "traefik.http.services.losi-online.loadBalancer.server.port=4321"

networks:
  proxy:
    external: true
