endpoints:
  - name: Forgejo
    url: https://git.ocd.beauty
    conditions:
      - "[STATUS] == 200"

  - name: Navidrome
    url: https://music.ocd.beauty
    conditions:
      - "[STATUS] == 200"

  - name: Woodpecker CI
    url: https://ci.ocd.beauty
    conditions:
      - "[STATUS] == 200"

storage:
  type: sqlite
  path: /data/data.db
