services:
  woodpecker-server:
    container_name: "woodpecker-server"
    image: "woodpeckerci/woodpecker-server:v3.18.0"
    restart: unless-stopped
    networks:
      - default
      - proxy
    volumes:
      - "var_lib_woodpecker:/var/lib/woodpecker"
    environment:
      - "WOODPECKER_ADMIN=${WOODPECKER_ADMIN}"
      - "WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}"
      - "WOODPECKER_DEBUG_PRETTY=true"
      - "WOODPECKER_DEBUG_NOCOLOR=false"
      - "WOODPECKER_FORGEJO=true"
      - "WOODPECKER_FORGEJO_CLIENT=${WOODPECKER_FORGEJO_CLIENT}"
      - "WOODPECKER_FORGEJO_SECRET=${WOODPECKER_FORGEJO_SECRET}"
      - "WOODPECKER_FORGEJO_URL=https://git.ocd.beauty"
      - "WOODPECKER_GRPC_SECRET=${WOODPECKER_GRPC_SECRET}"
      - "WOODPECKER_HOST=https://ci.ocd.beauty"
      - "WOODPECKER_OPEN=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ci.entryPoints=webSecure"
      - "traefik.http.routers.ci.rule=Host(`ci.ocd.beauty`)"
      - "traefik.http.services.ci.loadBalancer.server.port=8000"

  woodpecker-agent:
    container_name: "woodpecker-agent"
    image: "woodpeckerci/woodpecker-agent:v3.18.0"
    restart: unless-stopped
    networks:
      - default
    volumes:
      - "etc_woodpecker:/etc/woodpecker"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - "agent"
    environment:
      - "WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}"
      - "WOODPECKER_DEBUG_NOCOLOR=false"
      - "WOODPECKER_DEBUG_PRETTY=true"
      - "WOODPECKER_SERVER=woodpecker-server:9000"
    depends_on:
      - woodpecker-server

networks:
  proxy:
    external: true

volumes:
  etc_woodpecker:
  var_lib_woodpecker:
